[FIREBASE_SERVICE_ACCOUNT]
type = "service_account"
project_id = "sports-2f624"
private_key_id = "342daa2759ba0e4a065a6dd410bd3c68d180dcfd"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDbyNsx+GeU7Ma7
e5B4JlKoIzBzDZVF7LNM/GK9+pBZNxD2DtIPYLxhn9fZBzgITHkZuNFkYYOjUX9F
RhSklD/sncwH938KUgKHwrkYjyQ8W1w9MqHx/OkRIN1A8zc0WzL/RHZF2l+ZfUSs
Jpvdv6xZel4i5I3r/NA5cqWbrs0LJIen8YJVFtRyndBZCIjmC6H6lG5LVp1nsO2C
H6jvcmqTTyohuNG8pua9j6BHEjxn5GdUb5CMY/KoZAI+Pn9ymd+Xev/nm47MnYkD
CU9ht4cfZi5o/Jcb48MLvLQHZw3S6lQR5h9GW/ik8KptbEc/WXL9s2XnU9V0tJOq
auDu/YqdAgMBAAECggEABs4UxLAmxjcrPhHThXeA9qtu7BkJu/+vW4ey/Pky7/g4
V7iva1d47bg3xC9TiPo+g6aJITJdvjhJ7a3/pKA3Ic85n9jbakk4woBWdSVgH1hK
0QBDgGJuyvTOtPHy4yBHF3KaC4v5NXTp+T88HeUPOTlZ4dBcI+g7gD6FqdODOMA1
mLK/DYSAAzsxgBDYyEojpkuB6GXDFP4vYEpIJrEQOV1DRWYCd/YuNW5dg4TW5RJO
5O1BeqBnlMjiRdZkmPoWrMzBlCLuliWGHRWK7wexr/dHw3ym5gDTGSK7kqO7ojlT
jD3OdR+4C3cGhJ2uI+2fPODnHF7EDNB0pJZUhuEDpwKBgQD4b+5aRmO0hXnk1DF6
usj6BuscCX+11a8p1qVSHLisAThuxb7FBieXqKo1olLYsKVAvbgx1ugyEJ3Q5Mzt
ZYTwrb1YKU009G2ECIU5MBJnXyx9HTwJtnyFTUSPKxAh5MqYGSY8sY80fstmxe6X
5UdfK5eIRqfjgJUMK8K30++D5wKBgQDieaKs5E2gA0bGKfCfNwYw4syZfJEOdWXe
MAgA3o68A7f9UhnRFbVY2E8VKeLZ9cvoYhaswPqJwJzIsVB2L6Wu0RXQgbSuRxxI
3DJf7OSDWuw+SclK+WcvtAT0WOJWDq2mtIPpsnI+/Bq2BYoUVFF5FdFuvY6PVAvV
KXXQCLQs2wKBgFec4ankePUIvVv9mRV3GblTB0bz8p3lpchTcinrBxVhuM0X35cL
/Jp3WM9hV2YjpaOXRIYPDAPb6Evq5Hoz+xYFr2iP6DJsoNKXTqREV7kszzuwO6QR
PwijnzH+Nco+LVRGSj3NQHt627B6zRG0Qd9GOEJO6JZKmkWYiSrbCvSxAoGBAIQC
tMEknt7LqiBuZ/TWhQRP30UEaCVOZx+ZTcD7+aU8Ya4Ggkfu6HMuOwKyFKpJ7R66
ntk7ieed736fYO3d4lJIPDDEqud/wUVtjBvYFRroOcLBqICxUrkIPI+guO1hAXBZV
GKNLQe7W0tcQ6YiqEYeMITT0xzlimzcYYLTvrd6LAoGAJm7DSlqHeIDQhiuXN6al
lBcdG/WROQq61JfU9YIckTnUWtox6H2WnGXxIIru1HCYdj1BA20q7dMOVCnKMEbv
fcqh9QQsYqkCS4m4y+msqDhvzkrP5tmiGRMFlqCy5iQiKO3VvZUQRoCR9/MHJfAg
atZW0EFgRFyC6Vx6XwUsoV4=
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@sports-2f624.iam.gserviceaccount.com"
client_id = "106960772383181539172"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40sports-2f624.iam.gserviceaccount.com"
