[firebase]
type = "service_account"
project_id = "sports-2f624"
private_key_id = "250d6064e396131ca2f9cca6eeaa762a3349e374"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCmSL5LKNdpOTRQ
...
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@sports-2f624.iam.gserviceaccount.com"
client_id = "106960772383181539172"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40sports-2f624.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
