[firebase]
type = "service_account"
project_id = "sports-2f624"
private_key_id = "eb59154d17c61af57b2937e0d03414e680d64dbf"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDV0+T13xUU1mFP
95TsdfPNklp72QsjVUbBGCAPLl3VUBth+4ljXzDvmEPxgjIxz1DRH+02Dm/3saWN
JNlqsf4Q5+dNZIrmI18Nv+JM69uCw4Mdtg9Hn6oay6VGrQh+TOeGW8KAQSzPKjVu
NYaTkP2PKiEboviQe7OojrdZuy8ZKzvPb4dd2t1nehJ344ojHOa8t+vlGOfTE02V
59F0zpscs20aiti+LEmHGBY46eM+Q6moafC1c8kD5FQZxjUE0OZQLo5EepfjaBgq
80Pgb9G2HvuG0pa6DCbTjCPxrJomF6i04XVGMUsjaiT5EKX1YOYrzXT96mrYC2Dh
eQjZLN3nAgMBAAECggEAWOWv3nKhEpkwOu1NGmPNeQ1cFfo90bI96MBtb7JQq4MS
51EKpOgp8aqFsM32rVOqH09dMOier0VJdR05UMzwOjoXpUrkHlrdRVudq2oxSDOd
esg6oQXl1B8PNwtwKQYzCV5zxhuSlAxRy2Bwc0BH0nHq8tD18yeioTS4UJNsONNI
hFFkSR2iXrJoVsp0CmyrU5qVla8QgD7J5hNm++gvGX4fMERjlv2rkq+yNdZcM4od
0UBsGnd/t600Th4BvhXzp2ihOZxtyB0QjwVmaGb/AHKBvEZotbB8a5uQAh9inu8O
+KMdbSHloeioMCvhbCY5EyCLHf+7HORRawNNw3MqlQKBgQDu6vI9SIbaFLdjeRrt
UZT7o+JI6GfkzKICoBuQ023CIp/cXGtS1HEAz/y8JvludKTuxv49lU9mtXHA3LSE
67IrVP18SkARHPG+ArWdkR2MIhaX5GRVqz1cKVVqn3bbo0+/NJ2gqNJQLDn6JUZn
KpgaD5tzPJvnddzsK6pt9hztywKBgQDlHbXI5tf8Mr8o6+GmJRW+fjg887GUGe5j
+jwIVnvMkEAkQGTRV8RTqaBNT3Ywh1vKqqQ5wfMCA0+Uvlio3gTtc5hN4wsURPjh
XrQRrSg7S5F+iCBFG0FX0M6IrFM69WlXL0OIsfQ26EPa5lFUw4GK+wSb9i/n2cGr
Z3auoTCM1QKBgQDtlV+sh3nqVd2EIsMfKhiAIJl+rPXbtY6KE9M1srqb6jiUNqdX
KADzsOB/7jXunDoDZIkgjmD2Hwruocs1vvhfVNX6ChAptGHE9QbLmKoMVz2mcC1C
b9XF1yikrczRX1aHKnhxclAp/8DrurOHFflJOSn5b1UN18wIYufJD4v2/wKBgQCg
NAsFJCzIAq/ZrD4Gz42JunYWYIu9s/gV3kYVymscGY1QC9qy6nyzxzr4c+R/gFY1
uuXEIRKLSMdfiU0zHrMxWY+YfnYjwSqJY4/jgEFOXMOqRwLRb4JcJfwUYvJ7mlgD
B2Bgd5X8wqGXsU4TR/UPuf96EkVjB8c808aPytPI1QKBgD5gSKQ4i3HYBDfSANNk
LSOPwufePR/+r5KtD4fEK7Nien8N1GmWvLM8uLsQcPmdc5AHrYovYK2lEWxfWqs1
Q0mfDNgBj7R2HATToTx1YgvxkvmpwL/zrOziW7eOnwm644be8gmpdV679RiNaEpn
fzoRLJ4W/4I04xgk7Y6LtjKs
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@sports-2f624.iam.gserviceaccount.com"
client_id = "106960772383181539172"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40sports-2f624.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
