[FIREBASE_SERVICE_ACCOUNT]
type = "service_account"
project_id = "sports-2f624"
private_key_id = "250d6064e396131ca2f9cca6eeaa762a3349e374"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCmSL5LKNdpOTRQ
3RZPEUrxmSXzaD4PMQiMkVvSKJO+9zxBG4l4OMqpV085j8sn14vPrf7td52Pxw/k
fA4vrVJcAXkXXNpoFTZ9VtBNRFRjvtbmEDfW0QxeyHRuDpDZmMLxKSxYwI/FsWC/
fx2elyIw+re19seRn3xTphF4ejAIi/Gm9bE9e6hpPf4oRrP16FneqcukVNo8pUCM
ZsCrFY1dtKBsIQlnHjW02dCL688L6++tMv5RjgeMad+NJig0sZKCO005/sfnwIIT
EsXYcXTSNMuTjwK+eSLezgvBAPWyqA+CC9ubRtaT1MCncFtWtB82lTAJ+SDiTzeN
vZvQB8JfAgMBAAECggEAE3DBvqvBs22arjGK4CeXaXOMOk7foosLAtQjtghEbbkd
9Eax5bpOB0pL2uDy0W+jyt3+xeiMJTkSpJXUWsKatGL/szmJ101Tl4fExqPMcfTn
zvHqdVTva01oP024pZf0gplbs+yfYm+AbiMAZYAp4SwOulllr6LDuEvcEwfGAdma
KgNvao+14Ps/WPsOvoTFv1YChF8uEA0UEv9RZi1GjQqAv/1Pcl0/DGWNlpE+Ldhn
kT9lBBkiwztwN6KuAoJlcMPwOhZWSCio7CylRIPZmmMMGd640WRYxyhPde8b4CHe
cCm8yAVFBGjawHmSM2O7siIQoWJqyuSJmgjb3DC94QKBgQDjDcPjxXbXatst20Po
I8zoXETQshxHpnWjEP0/vtRI6BZ4aWTN95+NCagZzqu9LkpdZAWN3LN6oKAtOrWZ
sM69HCQoeSHjMCIg+yXVCQwEq5tsYAHOAo/HBfN3XJbRv/m7YL8wBPjoPdZor0CL
dFJQWERim8oda17X2QhbyXc6WQKBgQC7e6wKnLvlwKuj2xBNvUZEqtSlmZ+ZfsJ9
Efw7+mYhKoo/+9m4VtBWJ2YJdmPLmR4mT6CRJmXqQsj62zJsQw3NeY6GDBZIRHNg
Mmbpa7myxANWWZ0FJuxtTfVsBdczz3lAe6OCTGVrCfPyfMDc4fu7j5sVnjHQb0bT
oAtSbw5bdwKBgQC40WGcrAV6f859WzfBZDLNCR4yymheok6rN48NLmZaGiEATrnx
Nhk3kp60sxf0XBPIRTyIJxgpP0pixqE/wz3ljVyZXVCKP4noUsaOzFhuDMnsw5F0
gX1LQbrWdBWIEr5TGgNGMSXy1TML72uYmEzQfajco3c3z0haZp15KVrVsQKBgDYm
jVVvWbINiUXFcxsRDSeuM8c07O0XuLMJK9JjC3aO4+mBI6xjnr8TmBwpjr9ylUu5
egYSkiMscQJLp2+vml/7uResjA8Jfk2NoT3QOI2Soegh8AFZ8bXMa5NsyHCVf08J
pvtud2iIMmaac9YYi23sF34R+A9c5JchRcPkgcAXAoGBAMwJg5ekKfYCUh/G5VtD
1qIplZxJ1PSCrEXb4xZuiePyUh2nfu+j7uQaymJ+VrvvY3mQuiGvCDdiU+Peb2zj
A+O+qeODJyHJdLL3qs2ly2g16wDrwGErJ7xUcAzPt4Z12DDFmVW9u5zHSnTy3O+b
RoDgQjifmpmYsmLZv+0M6dl+
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@sports-2f624.iam.gserviceaccount.com"
client_id = "106960772383181539172"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40sports-2f624.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
