[firebase]
type = "service_account"
project_id = "sports-2f624"
private_key_id = "0e92d0d94cc6c2ad08080c6c4d72c7e4ed4b9748"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC6BuEGdE6Q8bPX
KR0eaKHfAkCa/vpYiNp3Ul69956HlrU6/M8dqW1J4wtfBu31xGPZe6DCz3VYWuYW
Iu7Z9mZdU4X2BUrEhLPQNg9fmA44J9Ohe084t6pSS+4ZTYEVW2vX13GXx+SfhSJ9
jw/unZnDVxfRpnX5GikNSgL86A9NOk/qvaveInt09Ym6DQAm3QHqJNHZDSfyylCG
CzSG3dvyhljbtzL/NvQ708ZOu4eRpchvWPzhKPfUDsBLOTqRsA6Q1zpyUDVyvsNX
lKNAq/xXH8jwGM+opej+WIwdyEEmY7UA0gbxj0Yi4wc83aiHd+k7Fb6KeOTARmS5
NvcLSJ3JAgMBAAECggEAFaJVKyX9jm0S6Ck3jLYdv8yy7L5N07FeuX+9Ku864t6L
sbzS7XUrE5ZcV9nQyhiOhYK+KHRuBi9+u1ZRXCHZYm3N54BSuKtiKgsPcKOYtmko
peABpOv0hTZKuMCYYX53T+vAodE1F7l+UFyB6CiF8v9pnWUe1TB4qRCmwPjP8WrC
2at9w1EkV3/VB26FS7HgQ+2OWhqy35AxPZFug76EOgCNpCqTn+rrXxOnfNOJorfQ
XQnd+TzEKUN5Pw75sjz5Q8GSTZwVH4MkzgY8qHTVqQ+nUKSfgLAfCvaGvgUyAcY1
BO1r2yFD2UMqhI8WtKIq77snf7voW/mmxYn9RGXvrQKBgQDkXAyeI5WXaOaLz2lT
nkMYVGkIzCcV4PwHvzUv78qpISKk10U0Hbw8Yeu7p+Da6TNT+ynP7vHV6N4h80FC
o8eVHoaupQcR8DmFTA7RkAQ+AnYcWinI7/B3VCg6NEmCNy53rRCuyhqkXRPulwGu
31oYZ+McPoX4RiCi9U8MkjWp6wKBgQDQixvLXUdF/exVTgrvHCCMKNth97bBo4he
9ABH1uoWVCVAeKduQTMKuakfZ4zhF5k8UkCQEshSbj3vnvp2VoCf2ONZGYHg6uSq
7uGu2MQFYo7QKxRnwmI4igljwGhGNRNyACOH2oXUdlxPPQVB+2Lxqq0FxzovIbsq
tipCdjCWGwKBgQDF5gu9RENQasVZJk81+vJUdFpuGFZK/KYNpKPYPivYNHIMfs5n
YtmNTqL3Bn6z1+L2hbRvkbic02kl7OSCduLwlPrNARFGd3Ox0/8Hl5JFluZ6nZyW
mXFASHtwLX4CzgWEC0Ro5Zb/F/a9DrqTrNYsTmOgR4LcbRG9h2+RCmhdLwKBgQDE
a3GXXtkFrH+PbT1RLx3cxZK0OFvTEJMeVBV7lInQ1BpuGfYhG5nWrT4EzURcshxr
O1GCIZ66PQlrC0L+eMUXSXIA9sxkqvkLoonAZHxkUgsPOLQ0clqOxDzJzmyoS89v
3X+ZspHApmaVX3T3S65KzqW+voIn6E5gkUlGZgmnJwKBgQCrw9Zf/we8PKupq1NI
Os3cWTp0cNQoRj/JmFnikxKVW8kvziK6VROlK908fpGlgvX6cprvJ0TEa+j/Rvl2
G4nXintTZKq3CJ1cWIYPuH6q0QMzoFYplFEYUQfnR4kdmkC3ZPrAFgWdd04XFXv5
qllBK8oO75WvxjsIjSw99b2Dlg==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@sports-2f624.iam.gserviceaccount.com"
client_id = "106960772383181539172"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40sports-2f624.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
